# Generated by Django 5.1.2 on 2024-10-31 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmruthaRestaurant', '0003_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('digital_wallet', 'Digital Wallet')], max_length=20)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('digital_wallet_type', models.CharField(blank=True, choices=[('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('samsung_pay', 'Samsung Pay')], max_length=20, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart_items', models.ManyToManyField(related_name='orders', to='AmruthaRestaurant.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmruthaRestaurant.user')),
            ],
        ),
    ]
