# Generated by Django 5.1.2 on 2024-11-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmruthaRestaurant', '0007_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
