# Generated by Django 5.1.2 on 2024-11-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmruthaRestaurant', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='customer_read_status',
            field=models.BooleanField(default=False),
        ),
    ]
